### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [stevenbenner/interfacelift-downloader#22] opened 2018-07-09 14:15 UTC
Got this error after downloading 155 from about a total of 3000 images

`[3088] Saved: 04007_autumnsunlightthroughthetrees_1280x1024.jpg
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)`

**Comment by Karlheinzniebuhr** [comment] 2018-10-13 13:03
it is pretty pointless to report bugs when getting this kind of attitude

**Comment by stevenbenner** [comment] 2018-10-13 19:46
Sorry for the delayed response, somehow I missed this github issue.

I cannot reproduce this problem. Does this happen every time you run the script? If so, does it fail after the same number of files? If you wait a while does it start working again?

I'm thinking that it's either a connectivity issue or you're running into some kind of rate limiting from the web site.

**Comment by stevenbenner** [comment] 2018-10-13 20:12
Reopening as a possible improvement.

Yeah it would probably make sense to catch any errors thrown by `http.get()` and print out a more user friendly error.

I think some retry logic would be a good addition to handle a randomly dropped connection. If it fails with a connection error then wait a few seconds (probably implement [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff)) and retry, repeat up to some limit then fail. This would make it all around more resilient to random failures.

**Comment by stevenbenner** [comment] 2022-02-05 20:26
Fixed - or at least improved - in commit `0357eb2e3187525dd3b7e18273d3c7d173ba6131`.

I have added error handling to download operations that will catch connection errors and retry the download after an increasing delay. The retry is limited to 3 attempts, after which it will move on to the next file in the download queue.

This fix is included in the latest 2.4.0 release.

**Closed by stevenbenner** 2022-02-05 20:26 UTC
Labels: enhancement
